Maven
j123b567/java-intelhex-parser pull request #9
Opened 2023-02-24 12:47 UTC by ZZerog

Hi,
I restructured project into Maven project. Rename some of classes so example in readme is now copy/past executable.

2023-02-24 14:44 UTC, ZZerog commented
Ok, I did new commit and rename classes back (readme as well).

I think that IntelHexParser is better than Parser, because when include this library into other project, class Parser tell nothing about what 'Parser' do.

PS: pozdrav z Brna

2023-02-24 15:48 UTC, j123b567 requested changes
I no longer use Java and maven never worked for me in the past (10 years back) so I don't have real experience. Please correct me if I'm wrong.

PS: Pozdrav od Hodonína :-D

2023-02-24 15:48 UTC, j123b567 commented on pom.xml
> +  <url>https://github.com/ZZerog/java-intelhex-parser</url>
Should be upstream URL

2023-02-24 15:48 UTC, j123b567 commented on pom.xml
> +              <artifactId>maven-jar-plugin</artifactId>
probably missing something like
```xml
<version>2.4</version>
```

Maven complains with
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for cz.jaybee:intelhex:jar:1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 46, column 19
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

2023-02-24 15:48 UTC, j123b567 commented on README.md
> +`mvn clean install`
Not sure about this. To just build the project, `mvn package` (or with `clean`) should be used. Which corresponds with the following "Run demo".

So probably splitting it into multiple sections would be better. Title of the readme can be converted to `#` from `====================` so the following structure make more sense.

I propose something like this. What do you think?

```markdown
## Build

`mvn package`

### Run demo:
after build go to the target directory and run:

`java -jar intelhex-1.0.jar`

## Install the package to the local repository

`mvn clean install`
```

2023-02-24 16:12 UTC, ZZerog commented on pom.xml
> +              <artifactId>maven-jar-plugin</artifactId>
Newest is 3.3.0
https://search.maven.org/artifact/org.apache.maven.plugins/maven-jar-plugin/3.3.0/maven-plugin

2023-02-24 16:20 UTC, ZZerog commented on README.md
> +`mvn clean install`
Nice. Yep, correct.

mvn clean - delete target directory
mvn package - create jar
mvn install - do whole phases ..more here https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#a-build-lifecycle-is-made-up-of-phases

2023-02-24 16:26 UTC, ZZerog commented on pom.xml
> +  <url>https://github.com/ZZerog/java-intelhex-parser</url>
Yes, correct is 

https://github.com/j123b567/java-intelhex-parser

2023-02-24 16:44 UTC, ZZerog commented
Check new commit

2023-02-27 13:53 UTC, j123b567 approved these changes

2023-02-27 13:53 UTC, j123b567 commented
Thank you!

2023-02-27 13:53 UTC, merged